passThroughZMin: 0.0
passThroughZMax: 1.5
voxelGridX: 0.04
voxelGridY: 0.04
voxelGridZ: 0.04
minRequiredPointsOnLine: 3
distanceToLineTresh: 0.1
refineSurfaceRequired: true
worldFrame: /map
clusterHeightTresh: 0.1
clusterTolerance: 0.075
clusterMinSize: 50
clusterMaxSize: 200
angleDeviationToXYPlane: 0.3
setup: hector
distTrashSegmentation: 0.05
maxDistBetweenStairsPoints: 3.0
